### PR TITLE
Add run_if_resource_added and run_if_resource_removed

### PR DESCRIPTION
**Pull request by Shatur**
In some cases such helpers may become handy.

### CODE REVIEW

**Comment by lecoqjacob** [comment]
Latest commit was in April. I wonder if this is still actively maintained.

**Comment by inodentry** [comment]
@lecoqjacob your comment is not helpful.

Yes, the project receives little attention. This crate was created as a "temporary hack" until Bevy has its "stageless" functionality implemented. Also, my life is kinda hectic and I don't go on my computer to deal with open source stuff often. I will get around to things eventually.

Please don't go posting discouraging comments on other people's projects and contributions. It helps nobody.

**Review by inodentry — CHANGES_REQUESTED** [review]
You have added this only for ConditionSet. It needs to be added/duplicated in a bunch of other places (it is ugly, i know): trait IntoConditionalExclusiveSystem (around line 540), trait IntoConditionalSystem (around line 450), trait ConditionHelpers (around line 350).

I couldn't figure out the github UI to nicely highlight all these places for you.

**Comment by inodentry** [comment]
Another thing worth pointing out is these run conditions actually don't really accomplish anything more meaningful than if you were to just add your system unconditionally, and do the check inside your system. I guess your PR just creates an arguably more convenient syntax. But this API could be misleading, as people might think it improves performance by saving the need to run the system, which is not true.

Currently, as `iyes_loopless` does not modify the bevy scheduler anyway, systems with conditions attached to them will actually always run anyway. Adding the run condition does not save you the overhead of running the system. This is a major perf limitation of this crate, and a big reason why the "real solution" is to push for real Stageless in Bevy proper. This crate cannot save you the performance overhead. You are running all the systems all the time.

The run conditions effectively behave like just a fancy early-return mechanism. Bevy will run the system (spawning a task on the thread pool, etc...), always, as if it was just a regular system that always runs, and needs to potentially access all the data from all the combined system params of all the conditions + the internal system function. `iyes_loopless` just creates a fancy system that will call the conditions first and then not call your provided system function if a condition fails. If anything, using run conditions has *more* overhead than just doing a check and early return inside your system.

**Comment by inodentry** [comment]
Thanks. <3

Yes, there is value in having nice syntax sugar. I'm convinced.

Merging.

**Comment by Shatur** [comment]
Thank you! May I ask you to draft a new release?

**Comment by inodentry** [comment]
I will look through the issue tracker for things that could be easily addressed, and then yes. :)

**Comment by lecoqjacob** [comment]
> You have added this only for ConditionSet. It needs to be added/duplicated in a bunch of other places (it is ugly, i know): trait IntoConditionalExclusiveSystem (around line 540), trait IntoConditionalSystem (around line 450), trait ConditionHelpers (around line 350).
> 
> 
> 
> I couldn't figure out the github UI to nicely highlight all these places for you.

Apologizes I meant no harm was generally curious.

**Pull request merged**
